livraison_livraison:
    resource: "@Log210LivraisonBundle/Controller/"
    type:     annotation
    prefix:   /

livraison_user:
    resource: "@Log210UserBundle/Controller/"
    type:     annotation
    prefix:   /