dashboard:
    pattern:  /{_locale}
    defaults: { _controller: Log210LivraisonBundle:Dashboard:index, _locale: fr }
    requirements:
        culture:  en|fr
select_lang:
    pattern:  /{_locale}/select_lang/{langue}
    defaults: { _controller: Log210LivraisonBundle:Dashboard:selectLang, _locale: fr  }
    requirements:
        _locale:  en|fr

log210_api:
    resource: "@Log210APIBundle/Controller/"
    type:     annotation
    prefix:   /api

livraison_livraison:
    resource: "@Log210LivraisonBundle/Controller/"
    type:     annotation
    prefix:   /

log210_order:
    resource: "@Log210OrderBundle/Controller/"
    type:     annotation
    prefix:   /

livraison_user:
    resource: "@Log210UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
