# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    livraisonBundle.restaurantService:
      class: Log210\LivraisonBundle\Utils\RestaurantService
      arguments: ["@doctrine.orm.entity_manager"]

    restaurantRepository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Log210\LivraisonBundle\Entity\Restaurant